@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title C4_Component_Diagram_AccountMGM — Система управления аккаунтами


Person(user, "Пользователь", "Пользователь системы Warmhouse")
Person(admin, "Администратор", "Администратор системы WarmHouse")

System_Ext(WebUI, "WebUI", "UI для управления системой")
System_Ext(API, "API", "API взаимодействия компонентов системы")

Container_Boundary(AccountMGM, "Система управления аккаунтами") {
    Component(AMS, "Account Mannagenent System", "CRUD операции с Пользователями, Домами, Устройствами")
    ComponentDb(AccountDb, "Account Database", "PostgreSQL", "Хранение таблиц Пользователей, Домов, Устройств и связей между ними")
    Component(AuthService, "Authorization Service", "Осуществление авторизации, управление ролями и правами доступа")
    Component(MessageBroker, "Message Broker для событий пользователей", "Message Broker", "Публикация событий с Пользователями, Домами, Устройствами для других сервисов")
    Component(LogService, "Logger Service", "Логирование действий пользователей для EventLog")
}

Rel(user, WebUI, "Выполнение действий с данными Пользователей, Домов, Устройств")
Rel(admin, WebUI, "Выполнение администрирования")
Rel(WebUI, API, "Отправка запросов")
Rel(API, AMS, "Вызов логики")
Rel(AMS, AccountDb, " CRUD работа с учетными данными Пользователей, Домов, Устройств")
Rel(AMS, AuthService, "Осуществление авторизации, управление токенами, ролями и правами доступа")
Rel(AMS, MessageBroker, "Публикация событий с Пользователями, Домами, Устройствами для других сервисов)")
Rel(AMS, LogService, "Передача данных об изменениях для EventLog")

@enduml